apiVersion: apps/v1
kind: Deployment
metadata:
  name: vreiheit-discord-bot-deployment
  labels:
    app: vreiheit
    type: discord-bot-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vreiheit
      type: discord-bot-deployment
  template:
    metadata:
      labels:
        app: vreiheit
        type: discord-bot-deployment
    spec:
      containers:
        - name: vreiheit-discord-bot
          image: ghcr.io/eyyy-nora/vreiheit-bot
          ports:
            - containerPort: 3000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: vreiheit-postgres
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: vreiheit-postgres
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: vreiheit-postgres
                  key: db
            - name: POSTGRES_HOST
              value: vreiheit-postgres-service
            - name: POSTGRES_PORT
              value: "5432"
            - name: TZ
              value: "Europe/Berlin"
